# Generated by Django 4.2 on 2023-05-16 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spav', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticeboard',
            old_name='created_at',
            new_name='notice_created_at',
        ),
        migrations.RenameField(
            model_name='noticeboard',
            old_name='title',
            new_name='notice_title',
        ),
        migrations.RenameField(
            model_name='noticeboard',
            old_name='updated_at',
            new_name='notice_updated_at',
        ),
        migrations.RenameField(
            model_name='noticeboard',
            old_name='uploaded_by',
            new_name='notice_uploaded_by',
        ),
        migrations.RemoveField(
            model_name='noticeboard',
            name='content',
        ),
        migrations.AddField(
            model_name='noticeboard',
            name='notice_attachment',
            field=models.FileField(null=True, upload_to='noticeboard', verbose_name='Attachment'),
        ),
        migrations.AddField(
            model_name='noticeboard',
            name='notice_link',
            field=models.URLField(null=True, verbose_name='URL'),
        ),
    ]
