# Generated by Django 4.2 on 2023-05-16 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spav', '0002_rename_created_at_noticeboard_notice_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slider/')),
                ('caption', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
